# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefas.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tarefas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtarefas.proto\x12\x07tarefas\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x0bTaskRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nuser_token\x18\x02 \x01(\t\x12\x14\n\x0ctask_details\x18\x03 \x01(\t\"@\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\" \n\rStatusRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"B\n\x0eStatusResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"%\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x13\n\x11HeartbeatResponse\"(\n\x12StateUpdateRequest\x12\x12\n\nstate_json\x18\x01 \x01(\t\"7\n\x13StateUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\";\n\x12\x45xecuteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x14\n\x0ctask_details\x18\x02 \x01(\t\"6\n\x13\x45xecuteTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\x91\x01\n\x10TaskOrchestrator\x12\x39\n\nSubmitTask\x12\x14.tarefas.TaskRequest\x1a\x15.tarefas.TaskResponse\x12\x42\n\x0f\x43heckTaskStatus\x12\x16.tarefas.StatusRequest\x1a\x17.tarefas.StatusResponse2W\n\rWorkerService\x12\x46\n\rSendHeartbeat\x12\x19.tarefas.HeartbeatRequest\x1a\x1a.tarefas.HeartbeatResponse2\xa6\x01\n\x16SynchronizationService\x12H\n\x0bUpdateState\x12\x1b.tarefas.StateUpdateRequest\x1a\x1c.tarefas.StateUpdateResponse\x12\x42\n\x10PrimaryHeartbeat\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty2]\n\x11WorkerNodeService\x12H\n\x0b\x45xecuteTask\x12\x1b.tarefas.ExecuteTaskRequest\x1a\x1c.tarefas.ExecuteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=55
  _globals['_TASKREQUEST']._serialized_end=127
  _globals['_TASKRESPONSE']._serialized_start=129
  _globals['_TASKRESPONSE']._serialized_end=193
  _globals['_STATUSREQUEST']._serialized_start=195
  _globals['_STATUSREQUEST']._serialized_end=227
  _globals['_STATUSRESPONSE']._serialized_start=229
  _globals['_STATUSRESPONSE']._serialized_end=295
  _globals['_HEARTBEATREQUEST']._serialized_start=297
  _globals['_HEARTBEATREQUEST']._serialized_end=334
  _globals['_HEARTBEATRESPONSE']._serialized_start=336
  _globals['_HEARTBEATRESPONSE']._serialized_end=355
  _globals['_STATEUPDATEREQUEST']._serialized_start=357
  _globals['_STATEUPDATEREQUEST']._serialized_end=397
  _globals['_STATEUPDATERESPONSE']._serialized_start=399
  _globals['_STATEUPDATERESPONSE']._serialized_end=454
  _globals['_EXECUTETASKREQUEST']._serialized_start=456
  _globals['_EXECUTETASKREQUEST']._serialized_end=515
  _globals['_EXECUTETASKRESPONSE']._serialized_start=517
  _globals['_EXECUTETASKRESPONSE']._serialized_end=571
  _globals['_TASKORCHESTRATOR']._serialized_start=574
  _globals['_TASKORCHESTRATOR']._serialized_end=719
  _globals['_WORKERSERVICE']._serialized_start=721
  _globals['_WORKERSERVICE']._serialized_end=808
  _globals['_SYNCHRONIZATIONSERVICE']._serialized_start=811
  _globals['_SYNCHRONIZATIONSERVICE']._serialized_end=977
  _globals['_WORKERNODESERVICE']._serialized_start=979
  _globals['_WORKERNODESERVICE']._serialized_end=1072
# @@protoc_insertion_point(module_scope)
